### PR TITLE
Change separator from \ to / when starting the repl

### LINKED ISSUE #100: Starting repl from file on windows does not work ( all path separator are removed from the path)
Even after #90 (I use v0.9.0 and had the same issue with the previous version), start or refresh repl still remove all path separator from the path. Example:
:l d:MyBackupsandboxidristestDec.idr
(real path been D:\MyBackup\sandbox\idris\test\Dec.idr)

### PR DESCRIPTION
**Pull request by Stilgar84**
Fixes #100

### CODE REVIEW

File: src/idris/commands.js [hunk 1]
```diff
@@ -354,12 +354,11 @@ let startup = (uri) => {
 
   if (innerCompilerOptions.src && uri.includes(innerCompilerOptions.src)) {
     term.sendText(`:cd ${path.resolve(innerCompilerOptions.src)}`)
```
Comment (zjhmale) [inline src/idris/commands.js]: Maybe the `sendText` here also need a `.replace(/\\/g, "/") `

Comment (Stilgar84) [inline src/idris/commands.js]: Your are right, completely missed it (need more sleep :))

**Comment by zjhmale** [comment]
Thanks!
